### ISSUE TITLE
Where do I get my user token?

### ISSUE THREAD

**Issue by eibrahim** [yannickglt/alfred-slack#16]
According to your documentation and the info at https://api.slack.com/docs/token-types#user, it looks like I need a user token.  But I don't see where I can get a user token.  I created a slack app but that only has a Verification Token which is not I need.

Thanks for doing this and I can't wait to make it work.

**Comment by yannickglt** [comment]
Hi!
You are right, the way to create tokens in Slack was deprecated and is not available anymore. I released a new version of the Slack workflow ([v3.0.0](https://github.com/packal/repository/raw/master/com.yannickglt.alfred2.slack/slack.alfredworkflow)) which handles the new way to add third-party applications working with Slack. You will get more info on the [ReadMe](https://github.com/yannickglt/alfred-slack/blob/master/README.md) on how to generate a unique client code.

**Comment by eibrahim** [comment]
I tried to generate code at http://yannickglt.github.io/alfred-slack/ and got this error:

```
OAuth Error: redirect_uri did not match any configured URIs.

Passed URI : http://yannickglt.github.io/alfred-slack/?client_id=3070385995.228667914977
Allowed URI : none specified
```

**Comment by eibrahim** [comment]
I figured out the problem.  You were missing a step in your instructions where we have to go to the OAuth & Permission section in slack and add a redirect url to http://yannickglt.github.io/alfred-slack

**Comment by eibrahim** [comment]
hmmm...  I am still having problems, when I try step 4, I get this 

![image](https://user-images.githubusercontent.com/143816/29502002-cc39d664-85fa-11e7-940e-b55539900a1d.png)

I restarted alfred and same issue.

BTW, I am using alfred 3.

**Comment by yannickglt** [comment]
You're right. I gonna add it quickly, thanks for reporting! 
For the issue, what is the list of commands available when you type only `slack - - `? Could you make a screenshot please?

**Comment by eibrahim** [comment]
Not at my computer now but I think it either has the same look as above or it just says "start slack workflow" and nothing happens if I click it.  

I never got any options or other choices to click

**Comment by yannickglt** [comment]
OK. Please join the [gitter](https://gitter.im/yannickglt/alfred-slack) when you will get time and I will try to help you further (if you want of course ^^).
